//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingridient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingridient()
        {
            this.IngredientsLogics = new HashSet<IngredientsLogic>();
        }
    
        public int Id { get; set; }
        public string NamaBahan { get; set; }
        public string DeskripsiBahan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsLogic> IngredientsLogics { get; set; }
    }
}
